
import './globals.css'
import { Menu } from '../components'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

    return (
      <html>
        <body>
        <div className=' w-screen h-screen bg-[#333333] flex flex-col justify-between'>
      <header></header>
      {children}
      <Menu />
      </div> 
        </body>
      </html>
      
        )
  
}
